import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import StoreProvider from "@/lib/storeProvide";
// import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mandi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathName = usePathname()

  // Check if the current route is a login or register page
  return (
    <html lang="en">
      <body>
        <StoreProvider>
        <Header />

        {children}
        <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
